services:
  - type: web
    name: moj-muzyk-bot
    env: python
    plan: free                   # zmień na starter jeśli chcesz Background Worker
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION

        value: 3.11 
        [phases.setup]
    aptPkgs: ['ffmpeg', 'deno']
